Correction of Clone Repository Bug
crewAIInc/crewAI-examples pull request #149
Opened 2024-08-22 02:15 UTC by CalebeMiranda

Remove the space between config_/agents.yaml and tasks.yaml. (Represented with "_")
To prevent error: invalid path 'screenplay_writer/config /agents.yaml' and error: invalid path 'screenplay_writer/config /tasks.yaml' when cloning the repository.

2024-08-24 03:35 UTC, theCyberTech requested changes
Can you please fix up the space in front of agents.yml then I can merge

2024-09-05 02:19 UTC, agrajagco commented on screenplay_writer/config/ agents.yaml
It appears there is still a space in front of the agents.yaml @CalebeMiranda

2024-09-05 02:52 UTC, agrajagco commented
I've created a corrective PR request, I've tagged @CalebeMiranda as a co-author

2024-09-05 11:38 UTC, theCyberTech commented
fixed in #157

2024-09-05 11:38 UTC, closed without merging